
class Error:
    def __init__(self,
                 message='',
                 old_location='',
                 title='',
                 file_name='',
                 series_name='',
                 e_nr='',
                 s_nr='',
                 s_nr_old='',
                 e_nr_old='',
                 update=True,
                 delete=False,
                 extension=''):
        self.message = message,
        self.old_location = old_location,
        self.title = title,
        self.file_name = file_name,
        self.series_name = series_name,
        self.e_nr = e_nr,
        self.s_nr = s_nr,
        self.s_nr_old = s_nr_old,
        self.e_nr_old = e_nr_old,
        self.update = update,
        self.delete = delete,
        self.extension = extension
